- name: Install node and npm
  hosts: webserver
  become: yes
  tasks: 
    - name: Update apt repo and cache
      apt: 
        update_cache: true 
        force_apt_get: true 
        cache_valid_time: 3600

    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create a new linux user for node app
  hosts: webserver
  become: yes
  tasks:
    - name: Create linux user
      user:
        name: opeyemi
        comment: ope admin
        group: ubuntu  # Specify the primary group
        
    - name: Add sudo privileges to opeyemi
      lineinfile:
        dest: /etc/sudoers
        line: 'opeyemi ALL=(ALL:ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'   

- name: Deploy nodejs app
  hosts: webserver
  become: yes
  vars:
    - location: /home/upsea/DevOps-prj/ansible
    - version: 1.0.0
    - destination: /home/opeyemi
    
  tasks:
    - name: Copy nodejs folder to a server
      copy:
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{destination}}/app-{{version}}.tgz"

    - name: Unpack the nodejs file
      unarchive:
        src: "{{destination}}/app-{{version}}.tgz"
        dest: "{{destination}}"
        remote_src: yes 

- name: Set permissions for the app-1.0.0.tgz file
  hosts: webserver
  become: yes
  vars:
    - destination: /home/opeyemi 
    - version: 1.0.0
  tasks:
    - name: Ensure opeyemi has read access to the app-1.0.0.tgz file
      become: true
      file:
        path: "{{destination}}/app-{{version}}.tgz"
        owner: opeyemi
        group: ubuntu  # Use the default group associated with the user ubuntu
        mode: "0644"        
 
    - name: Install packages based on the package.json (dependencies)
      npm: 
        path: "{{destination}}/package"
    - name: Start the application
      command: 
        chdir: "{{destination}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}