---
- name: deploy app in news namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present        
    - name: deploy nginx my-app
      kubernetes.core.k8s:
        src: /home/upsea/DevOps-prj/ansible/nginx-config.yaml
        state: present         
        namespace: my-app

